### PR TITLE
Update Browser/BrowserContext API:s to return Promise

### PR DESCRIPTION
**Pull request by allansson**
Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/grafana/xk6-browser/issues/1294

### CODE REVIEW

**Review by inancgumus — APPROVED** [review]
Wow! Thanks a lot! I'm not sure how to review this, though (too many changes! 🙄). So, I trust you 👍

**Review by ankur22 — APPROVED** [review]
So all the tests are ran concurrently now (at least the ones that work with promise), but within an async function which is awaited on.

Looks good 👍

**Comment by inancgumus** [comment]
@ankur22 

> all the tests are ran concurrently now (at least the ones that work with promise), but within an async function which is awaited on.

How did you get that?

**Comment by allansson** [comment]
> Wow! Thanks a lot! I'm not sure how to review this, though (too many changes! 🙄). So, I trust you 👍

@inancgumus Oh, I see. 

The reason for the amount of changes is that I wrapped all of the test-cases in an async function, because I had to do `const page = await browser.newPage()` and top-level await is not supported. Every line was changed because wrapping it in a function added indentation on every line.

Otherwise it's just updating the `ExpectType` to expect a `Promise` for the affected API:s.

I have run the tests and they all pass. 🙂

**Comment by inancgumus** [comment]
@allansson 

Got it 👍 Makes sense. I'd suggest doing each step in a separate commit with a description so that we can easily see and review the changes. For example:
- Adding the async updates only for `Browser`
- Adding the async updates only for `BrowserContext`
- Wrapping up things in an async function (with a description "why")

**Comment by allansson** [comment]
> So all the tests are ran concurrently now (at least the ones that work with promise), but within an async function which is awaited on.
> 
> Looks good 👍

@ankur22 The function is actually never executed, it's just linted using the typescript type checker. So it doesn't matter if you await or not, unless you want to continue testing on some return value (e.g. `await context.newPage()`). 🙂

**Pull request merged**
