### PR TITLE
Fix `ResponseBody` type to use `ArrayBuffer` instead of `bytes`

### PR DESCRIPTION
**Pull request by KOConchobhair**
This matches the behavior of v0.51 of k6.

---

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] [Run `pnpm test k6`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:

- [X] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/grafana/k6/blob/33d3caa7d1b6825873d6b1c98f1d5cbbb467dc9f/js/modules/k6/http/request.go#L134

### CODE REVIEW

**Comment by oleiade** [comment]
This is a result of https://github.com/grafana/k6-jslib-aws/issues/105 for context. We should establish whether we actually want to change this or not before taking action.

**Comment by KOConchobhair** [comment]
> This is a result of [grafana/k6-jslib-aws#105](https://github.com/grafana/k6-jslib-aws/issues/105) for context. We should establish whether we actually want to change this or not before taking action.

Sorry I have to disagree with you here @oleiade . It has nothing to do with grafana/k6-jslib-aws#105.

This types bugfix is to fix a bug in the currently released v0.51.0 version of k6. k6 http` does not return `bytes` it returns an `ArrayBuffer`. See this line: https://github.com/grafana/k6/blob/33d3caa7d1b6825873d6b1c98f1d5cbbb467dc9f/js/modules/k6/http/request.go#L134

**Comment by oleiade** [comment]
Hey @KOConchobhair 👋🏻 

It's okay, all I'm saying is that k6 is a big, older project, and there might have been a reason for us marking it as returning `bytes` instead of `ArrayBuffer`, and we should internally evaluate if there was a reason indeed, and if still stands 🙇‍♂️

> should be merged regardless of what we decide there
While I appreciate and relate with the intention, as I mentioned above, we need to evaluate on our side whether we can and want to do this before moving on.  

The reason I mention https://github.com/grafana/k6-jslib-aws/issues/105 is to make sure all the context is mentioned. In my case, this is related as we have been impacted by the return type of HTTP there.

**Comment by KOConchobhair** [comment]
okay cool gotcha, well I will be very interested to hear the reason if it turns out this PR cannot be merged as I did a fair bit of digging to discover it and really thought I was on to something here!

**Comment by oleiade** [comment]
We'll for sure give you an update as soon as we've cleared this up 👍🏻 

We appreciate the PR regardless of the outcome. k6 is widely used, and we're just looking to do our due diligence to make sure we don't break it for someone else out there 🙇🏻

**Comment by KOConchobhair** [comment]
Looks like this PR can be closed since my changes were merged upstream in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/69781 and I see them in master here in this repo. 

Also seems like the branch I'm targeting has already been merged upstream as well
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/69902

**Pull request closed without merging**
